### ISSUE TITLE
ValueError: No variable matching ___ for file ____

### ISSUE THREAD

**Issue by FabioSeixas** [julienmalard/traDSSAT#16]
**Description**

*First one*:

I'm trying to acess a `.CSX` file. However when I run `DSSATRun` function, receive the following error:
`ValueError: No variable matching "SLPX  SLPT  SLPO CAC" for file BP.SOL.`

The exactly same error appears when I try `SoilFile` function.
`ValueError: No variable matching "SLPX  SLPT  SLPO CAC" for file BP.SOL.`

The same error with `.WTH` file and `WTHFile` function:
`ValueError: No variable matching "CCO2" for file BCRU9601.WTH.`

About this *first problem*, I realised that `SoilFile` and `WTHFile` functions work with other files. However this is not true for `DSSATRun` function, what brings us to the *Second Problem*.

*Second one:*

Facing the problem above, I tried to put the experiment associated `.SOL` file out of the `DSSAT47/Soil` directory and see what happens. So, I run the `DSSATRun` function and:

`ValueError: No variable matching "SLPX  SLPT  SLPO CAC" for file IC.SOL `

If I put out the `IC.SOL` file and run again, the same error appears, but with another soil file in the message. I also tried other crops and the same error occurs.

**To Reproduce**

1. With the attached files in the correct directory (DSSAT standard), this is the code to reproduce the error (any of the three last lines):

```
tradssat.set_dssat_dir("C:/DSSAT47")
tradssat.SoilFile('C:/DSSAT47/Soil/soil_file.SOL')
tradssat.WTHFile("C:/DSSAT47/Weather/weather_file.WTH")
tradssat.DSSATRun("C:/DSSAT47/Cassava/experiment_file.CSX")
```

2. Version of traDSSAT: `0.1.3`. and Windows 7

3. DSSAT files

[cassava_ECO.txt](https://github.com/julienmalard/traDSSAT/files/4011885/cassava_ECO.txt)
[cassava_SPE.txt](https://github.com/julienmalard/traDSSAT/files/4011886/cassava_SPE.txt)
[cassava_CUL.txt](https://github.com/julienmalard/traDSSAT/files/4011887/cassava_CUL.txt)

[experiment_T.txt](https://github.com/julienmalard/traDSSAT/files/4011880/experiment_T.txt)
[experiment_X.txt](https://github.com/julienmalard/traDSSAT/files/4011877/experiment_X.txt)

[soil.txt](https://github.com/julienmalard/traDSSAT/files/4011878/soil.txt)
[weather.txt](https://github.com/julienmalard/traDSSAT/files/4011879/weather.txt)

**Expected behavior**
A connection with the file, without error.

**Comment by julienmalard** [comment]
Thank you for the very detailed description!

It seems that this was a question of some missing variables in the traDSSAT file specifications. I fixed them and released an update. So if you upgrade traDSSAT with `pip` it should now work.

If you are interested, here are the relevant lines that solved the problem (added a new test file that caused the problem, and changed the variable specification).
https://github.com/julienmalard/traDSSAT/commit/3bf1c601c75e1b7a9593e47e9df3286c8cf95460
https://github.com/julienmalard/traDSSAT/commit/be47b0848ed394793dff7e2a9e1445e1cc54cbe4

Looking forward to your next issue!
-Julien
