### ISSUE TITLE
Unable to read Summary.OUT 

### ISSUE THREAD

**Issue by tbvaleriano** [julienmalard/traDSSAT#35]
Hi, I am trying to read the summary output, but it gives me an error.

Code: 
from tradssat.out import SummaryOut
plant = SummaryOut('/tmp/dssatafazmgcr/Summary.OUT')

Error:

ValueError: No variable matching "WYEAR SOIL_ID...    " for file Summary.OUT.

**Comment by julienmalard** [comment]
Hello,

That's odd. Could you share the Summary.OUT file for me to take a look at?

Thanks!

**Comment by tbvaleriano** [comment]
Sure! 

I saved as txt because the .OUT format did not accept 


[Summary.txt](https://github.com/julienmalard/traDSSAT/files/12540505/Summary.txt)

**Comment by julienmalard** [comment]
Thanks for reporting this! I've fixed and published a new version to pypi (0.1.8).
I've left the documentation (`info=''`) blank for the new variables; if you happen to know what they mean please don't hesitate to send a pull request.
