### ISSUE TITLE
PlantGro.OUT

### ISSUE THREAD

**Issue by qianweihao** [julienmalard/traDSSAT#51]
Hello,  there are some errors that I can't solve：
StopIteration                             Traceback (most recent call last)
File [c:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tradssat\tmpl\file.py:205](file:///C:/Users/Administrator/AppData/Local/Programs/Python/Python39/lib/site-packages/tradssat/tmpl/file.py:205), in File._get_var_names(self, line)
    [204](file:///c%3A/Users/Administrator/AppData/Local/Programs/Python/Python39/lib/site-packages/tradssat/tmpl/file.py?line=203) try:
--> [205](file:///c%3A/Users/Administrator/AppData/Local/Programs/Python/Python39/lib/site-packages/tradssat/tmpl/file.py?line=204)     name = next(vr for vr in var_names if line.startswith(vr))
    [206](file:///c%3A/Users/Administrator/AppData/Local/Programs/Python/Python39/lib/site-packages/tradssat/tmpl/file.py?line=205) except StopIteration:

StopIteration: 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
[d:\download\traDSSAT-master\example.py](file:///D:/download/traDSSAT-master/example.py) in line 39
     [35](file:///d%3A/download/traDSSAT-master/example.py?line=34) from tradssat import DSSATResults
     [37](file:///d%3A/download/traDSSAT-master/example.py?line=36) out = DSSATResults('[C:/DSSAT47/Cotton](file:///C:/DSSAT47/Cotton)')
---> [39](file:///d%3A/download/traDSSAT-master/example.py?line=38) out.get_value('SLAD', trt=1)
     [41](file:///d%3A/download/traDSSAT-master/example.py?line=40) # Get results at specific time (day of year, days after planting or days after start)
     [42](file:///d%3A/download/traDSSAT-master/example.py?line=41) out.get_value('SLAD', trt=1, t=13, at='DAS')  # Get result at 13 days after start

File [c:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tradssat\mgrs\out.py:78](file:///C:/Users/Administrator/AppData/Local/Programs/Python/Python39/lib/site-packages/tradssat/mgrs/out.py:78), in DSSATResults.get_value(self, var, trt, t, at, run)
     [76](file:///c%3A/Users/Administrator/AppData/Local/Programs/Python/Python39/lib/site-packages/tradssat/mgrs/out.py?line=75) if f is None:
     [77](file:///c%3A/Users/Administrator/AppData/Local/Programs/Python/Python39/lib/site-packages/tradssat/mgrs/out.py?line=76)     try:
---> [78](file:///c%3A/Users/Administrator/AppData/Local/Programs/Python/Python39/lib/site-packages/tradssat/mgrs/out.py?line=77)         f = self._outfiles[c] = self._outfiles_clases[c](self.folder)
     [79](file:///c%3A/Users/Administrator/AppData/Local/Programs/Python/Python39/lib/site-packages/tradssat/mgrs/out.py?line=78)     except FileNotFoundError:
     [80](file:///c%3A/Users/Administrator/AppData/Local/Programs/Python/Python39/lib/site-packages/tradssat/mgrs/out.py?line=79)         pass
...
    [212](file:///c%3A/Users/Administrator/AppData/Local/Programs/Python/Python39/lib/site-packages/tradssat/tmpl/file.py?line=211) final_names.append(name)
    [213](file:///c%3A/Users/Administrator/AppData/Local/Programs/Python/Python39/lib/site-packages/tradssat/tmpl/file.py?line=212) line = _strip(line[len(name):])

ValueError: No variable matching "D    SNW0C   SNW1C
" for file PlantGro.OUT.

this is my example.py,
from tradssat import SoilFile, WTHFile, ExpFile, set_dssat_dir
from tradssat import GeneticMgr, CULFile, ECOFile

# Read, edit and write soil files
soil = SoilFile('C:/DSSAT47/Soil/AZ.SOL')

# Read and write weather files as well
wth = WTHFile('C:/DSSAT47/Weather/AZMC8901.WTH')

# ...and experiment files!
exp = ExpFile('C:/DSSAT47/Cotton/AZMC8901.COX')

# Access genetic coefficients by cultivar file or ecotype file
cul = CULFile('C:/DSSAT47/Genotype/COGRO047.CUL')
eco = ECOFile('C:/DSSAT47/Genotype/COGRO047.ECO')

cul.get_value('CSDL')  # returns array of all varieties' P1
eco.get_value('PL-EM')  # returns array of all ecotypes' TOPT

# ...or automagically!
set_dssat_dir('C:/DSSAT47')
gen = GeneticMgr(crop='COGRO', cult='IB0001')
gen.get_value('CSDL')  # Returns P1 for MZIXM cultivar PC0001
gen.get_value('PL-EM')  # Returns ecotype variable TOPT for cultivar PC0001

from tradssat import DSSATRun

run = DSSATRun('C:/DSSAT47/Cotton/AZMC8901.COX')

run.get_trt_val('INGENO', trt=1)  # Get cultivar for treatment 1
run.set_trt_factor_level(trt=1, factor='CULTIVARS', level=2)  # Change level of treatment factor
run.set_factor_level_val('INGENO', 'IB0002', level=1)  # Change value of a factor level (in this case cultivar type)

from tradssat import DSSATResults

out = DSSATResults('C:/DSSAT47/Cotton')

out.get_value('SLAD', trt=1)

# Get results at specific time (day of year, days after planting or days after start)
out.get_value('SLAD', trt=1, t=13, at='DAS')  # Get result at 13 days after start
out.get_value('SLAD', trt=1, t=13, at='DAP')  # Get result at 13 days after planting
out.get_value('SLAD', trt=1, t='1989 123', at='DOY')  # Get result at 123th day of year 1989

**Comment by julienmalard** [comment]
Hello,

Thanks for reporting this error. Can you share the exact code that led to the problem, along with all input files?

**Comment by qianweihao** [comment]
[example.txt](https://github.com/julienmalard/traDSSAT/files/13692741/example.txt)
hello, this is my example.py,I apologize for not being able to upload the py file, I converted it to txt format

**Comment by julienmalard** [comment]
谢谢！您能把文件也发给我吗？我没有DSSAT在这个电脑。
太谢谢您了。

**Comment by qianweihao** [comment]
[example.zip](https://github.com/julienmalard/traDSSAT/files/13694959/example.zip)
hi,this is my example file

**Comment by qianweihao** [comment]
Hello, I have troubleshooted and found that it was plantGro.out, the cotton file had a variable for RL10D but your file was RL10, after modifying it I was able to run it successfully. Suggest you make changes to the source file or I submit a PR

**Comment by julienmalard** [comment]
Thanks for the update! Sure, a PR would be most welcome. In your PR, you can also add a new test with the problematic plantgro.OUT file to guard against any regression in the future (let me know if you'ld like an example).

**Comment by qianweihao** [comment]
Hello, I have another question. Can your project call the DSSAT interface to achieve automatic run?

**Comment by julienmalard** [comment]
Hello,
Thanks; I'd been meaning to add this for a while and your message motivated me to finally get to it! You should now be able to call the new `DSSATRun.run()` function from the newest version of traDSSAT (0.1.9). Do note that I don't have access to a Windows machine at the moment, and so can't confirm that it works without glitches (and installing DSSAT on the GitHub Actions environment for automated tests would be non-trivial). If you come accross any errors, please do let me know! 

You can also use `subprocess.call()` to access the DSSAT interface directly if `DSSATRun.run()` has issues.
