### ISSUE TITLE
Unable to read Summary.OUT

### ISSUE THREAD

**Issue by taynaravaleriano** [julienmalard/traDSSAT#56]
Hi, the function SummaryOut() is not working for me anymore.
It gives the following message: 

ValueError: No variable matching "N2OEM  PI#M  PICM  P" for file Summary.OUT.

I am sending a Summary.OUT that I am trying to read.

[Summary (2).txt](https://github.com/julienmalard/traDSSAT/files/14201378/Summary.2.txt)

**Comment by julienmalard** [comment]
Thanks for reporting! It should be fixed now in version 0.1.10.
Please let me know if anything else bugs.

**Comment by taynaravaleriano** [comment]
Thank you! 


unfortunately I was unable to install version 0.1.10, it gives me the following error:

ERROR: Ignored the following versions that require a different python version: 2.1.0 Requires-Python >=3.9; 2.1.0rc0 Requires-Python >=3.9; 2.1.1 Requires-Python >=3.9; 2.1.2 Requires-Python >=3.9; 2.1.3 Requires-Python >=3.9; 2.1.4 Requires-Python >=3.9; 2.2.0 Requires-Python >=3.9; 2.2.0rc0 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement pandas>=2.1.4 (from tradssat) (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.4.0rc0, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.5.0rc0, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0rc0, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.0.3)
ERROR: No matching distribution found for pandas>=2.1.4

**Comment by julienmalard** [comment]
Hello,

What Python version are you using? We run tests on Python 3.12.
We also switched to pdm for mananging dependencies. Did you install with Poetry, pip or something else?

**Comment by taynaravaleriano** [comment]
I am using python version : 3.8.5
I installed with pip.

**Comment by julienmalard** [comment]
Ah, I think you need 3.9 or later. I'd recommend pdm for installation reproducibility, though pip should work as well.
